name = "easings_gleam"
version = "2.0.0"
description = "Easing functions for animation in pure Gleam"
licences = ["MIT"]
repository = { type = "github", user = "seancribbs", repo = "easings" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.5.2 and < 2.0.0"
vec_dict_ansi = ">= 1.1.0 and < 2.0.0"
vec = ">= 3.1.0 and < 4.0.0"
vec_dict = ">= 4.0.0 and < 5.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
